In [1]:
!pip install factor-analyzer

/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point


In [2]:
import pandas as pd
import numpy as np
from factor_analyzer import FactorAnalyzer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv('MMT Assignment - 1 STOMP.csv')
df.head()

Alternative                 Jazz                        Rock  \
0     7: Like strongly  3: Dislike a little            5: Like a little   
1   6: Like moderately   6: Like moderately            7: Like strongly   
2  3: Dislike a little  3: Dislike a little  4: Neither like or dislike   
3     5: Like a little     7: Like strongly            7: Like strongly   
4     7: Like strongly     7: Like strongly          6: Like moderately   

                         Folk              Religious  \
0         1: Dislike strongly  2: Dislike moderately   
1  4: Neither like or dislike  2: Dislike moderately   
2            5: Like a little       5: Like a little   
3  4: Neither like or dislike       5: Like a little   
4            7: Like strongly       5: Like a little   

                        Blues                 Heavy Metal         Soundtracks  \
0  4: Neither like or dislike  4: Neither like or dislike    7: Like strongly   
1          6: Like moderately            7: Like strongly    5: Like a little   
2          6: Like moderately       2: Dislike moderately  6: Like moderately   
3            7: Like strongly            7: Like strongly    7: Like strongly   
4            7: Like strongly         1: Dislike strongly    7: Like strongly   

                        Dance                 Pop                        Soul  \
0            7: Like strongly    7: Like strongly          6: Like moderately   
1         3: Dislike a little  6: Like moderately  4: Neither like or dislike   
2  4: Neither like or dislike  6: Like moderately          6: Like moderately   
3            5: Like a little    5: Like a little            5: Like a little   
4          6: Like moderately    7: Like strongly            7: Like strongly   

                   Rap                   Classical                     Country  
0   6: Like moderately         1: Dislike strongly  4: Neither like or dislike  
1   6: Like moderately         3: Dislike a little            5: Like a little  
2     5: Like a little  4: Neither like or dislike         3: Dislike a little  
3   6: Like moderately            7: Like strongly            7: Like strongly  
4  1: Dislike strongly          6: Like moderately            7: Like strongly

In [4]:
col_names = df.columns
col_names

Index(['Alternative', 'Jazz', 'Rock', 'Folk', 'Religious', 'Blues',
       'Heavy Metal', 'Soundtracks', 'Dance', 'Pop', 'Soul', 'Rap',
       'Classical', 'Country'],
      dtype='object')

In [5]:
for col in col_names:
    df[col] = df[col].str.extract('(\d+)')
    df[col] = pd.to_numeric(df[col])

In [6]:
df.head()

Alternative  Jazz  Rock  Folk  Religious  Blues  Heavy Metal  Soundtracks  \
0            7     3     5     1          2      4            4            7   
1            6     6     7     4          2      6            7            5   
2            3     3     4     5          5      6            2            6   
3            5     7     7     4          5      7            7            7   
4            7     7     6     7          5      7            1            7   

   Dance  Pop  Soul  Rap  Classical  Country  
0      7    7     6    6          1        4  
1      3    6     4    6          3        5  
2      4    6     6    5          4        3  
3      5    5     5    6          7        7  
4      6    7     7    1          6        7

In [7]:
scaler = StandardScaler()
df_standardized = scaler.fit_transform(df)
df_standardized = pd.DataFrame(df_standardized, columns=df.columns)
df_standardized.head()

Alternative      Jazz      Rock      Folk  Religious     Blues  \
0     1.624198 -1.191064 -0.161561 -2.298553  -1.732851 -0.753794   
1     0.805387  0.827128  1.152471 -0.429063  -1.732851  0.859590   
2    -1.651044 -1.191064 -0.818578  0.194100   0.121604  0.859590   
3    -0.013423  1.499858  1.152471 -0.429063   0.121604  1.666282   
4     1.624198  1.499858  0.495455  1.440426   0.121604  1.666282   

   Heavy Metal  Soundtracks     Dance       Pop      Soul       Rap  \
0    -0.008352     0.998399  0.967455  1.055871  0.597407  0.634270   
1     1.520154    -0.354986 -1.911313  0.306939 -1.320585  0.634270   
2    -1.027357     0.321706 -1.191621  0.306939  0.597407  0.081549   
3     1.520154     0.998399 -0.471929 -0.441992 -0.361589  0.634270   
4    -1.536859     0.998399  0.247763  1.055871  1.556404 -2.129336   

   Classical   Country  
0  -2.066504 -1.024191  
1  -0.965572 -0.156474  
2  -0.415106 -1.891909  
3   1.236293  1.578962  
4   0.685827  1.578962

In [8]:
df_standardized = df

In [9]:
from factor_analyzer import FactorAnalyzer

In [10]:
fa = FactorAnalyzer(n_factors=6, rotation='varimax',method='principal')
fa.fit(df_standardized)

FactorAnalyzer(method='principal', n_factors=6, rotation='varimax',
               rotation_kwargs={})

In [11]:
loadings = fa.loadings_
print(loadings)

[[ 0.22553393 -0.03716016  0.11831803  0.76151675  0.12797756  0.20671316]
 [ 0.31620132  0.52297478 -0.03058736 -0.19047529  0.51967811  0.18179169]
 [ 0.72653845  0.07405381  0.37199634  0.36883506  0.0058277  -0.00091494]
 [-0.10414378  0.1648995   0.04655294 -0.01531256 -0.06611445  0.88507505]
 [ 0.06890682 -0.04495985  0.12154184 -0.76389663  0.00894411  0.29544767]
 [-0.04397465 -0.16791519 -0.0051985   0.23532758  0.80522973  0.1040517 ]
 [ 0.87941063  0.05923287  0.00986322 -0.07210172  0.05944547 -0.09805403]
 [-0.07047344  0.23905728  0.59371348 -0.21464461  0.57740944 -0.13173814]
 [-0.03009896 -0.08555285  0.86583019 -0.06201136 -0.05718425 -0.04591218]
 [-0.1386223   0.60603659  0.30124306  0.36442912 -0.16984577 -0.29031687]
 [-0.64823152  0.23299184  0.08281838 -0.04097819  0.10411434  0.17492927]
 [ 0.36754574  0.06845633  0.59342109  0.30157508  0.06638612  0.12546532]
 [-0.21791215  0.05306151 -0.11873273 -0.06845777  0.43058281  0.7194076 ]
 [-0.08354685  0.80205791

In [12]:
loadings = pd.DataFrame(loadings, index=df.columns)
print(loadings)

                    0         1         2         3         4         5
Alternative  0.225534 -0.037160  0.118318  0.761517  0.127978  0.206713
Jazz         0.316201  0.522975 -0.030587 -0.190475  0.519678  0.181792
Rock         0.726538  0.074054  0.371996  0.368835  0.005828 -0.000915
Folk        -0.104144  0.164900  0.046553 -0.015313 -0.066114  0.885075
Religious    0.068907 -0.044960  0.121542 -0.763897  0.008944  0.295448
Blues       -0.043975 -0.167915 -0.005199  0.235328  0.805230  0.104052
Heavy Metal  0.879411  0.059233  0.009863 -0.072102  0.059445 -0.098054
Soundtracks -0.070473  0.239057  0.593713 -0.214645  0.577409 -0.131738
Dance       -0.030099 -0.085553  0.865830 -0.062011 -0.057184 -0.045912
Pop         -0.138622  0.606037  0.301243  0.364429 -0.169846 -0.290317
Soul        -0.648232  0.232992  0.082818 -0.040978  0.104114  0.174929
Rap          0.367546  0.068456  0.593421  0.301575  0.066386  0.125465
Classical   -0.217912  0.053062 -0.118733 -0.068458  0.430583  0

In [13]:
fa = FactorAnalyzer(n_factors=4, rotation='varimax',method='principal')
fa.fit(df_standardized)
loadings = fa.loadings_
loadings = pd.DataFrame(loadings, index=df.columns)
print(loadings)

                    0         1         2         3
Alternative  0.284048  0.247315 -0.029705  0.710944
Jazz         0.240504  0.601514  0.240419 -0.143318
Rock         0.721819  0.043047  0.307164  0.399909
Folk        -0.191824  0.687874 -0.082676 -0.022996
Religious    0.025522  0.178120  0.138642 -0.758023
Blues        0.129186  0.471897  0.023644  0.096949
Heavy Metal  0.837753  0.003929  0.068956 -0.054898
Soundtracks -0.002786  0.243327  0.767106 -0.170698
Dance        0.032487 -0.155647  0.744112 -0.007578
Pop         -0.243952 -0.122517  0.461448  0.537233
Soul        -0.663489  0.238418  0.146261 -0.008264
Rap          0.392115  0.140969  0.496395  0.334233
Classical   -0.202171  0.799969 -0.142779 -0.154569
Country     -0.291110  0.473431  0.147803  0.113587
